# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-auth-server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
        node-version: 12 # optional

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        curl -o- -L https://yarnpkg.com/install.sh | bash
        export PATH=$HOME/.yarn/bin:$PATH
        cd auth-server
        yarn install
        yarn lint
        yarn tsc
        
  lint-chain-db-watcher:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
        node-version: 12 # optional

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        curl -o- -L https://yarnpkg.com/install.sh | bash
        export PATH=$HOME/.yarn/bin:$PATH
        cd chain-db-watcher
        yarn install
        yarn lint
        yarn tsc
        
  lint-front-end:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
        node-version: 12 # optional

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        curl -o- -L https://yarnpkg.com/install.sh | bash
        export PATH=$HOME/.yarn/bin:$PATH
        cd front-end
        yarn install
        yarn lint
        yarn tsc
 
  build-auth-server:
    needs: [lint-auth-server]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Build and push auth server
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: niklabh # optional
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }} # optional
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: # optional
        # Docker repository to tag the image with
        repository: niklabh/kusama-polkassembly-auth-server
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: latest # optional
        # Automatically tags the built image with the git reference as per the readme
        tag_with_ref: true # optional
        # Automatically tags the built image with the git short SHA as per the readme
        tag_with_sha: true # optional
        # Path to the build context
        path: auth-server
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # dockerfile: # optional
        # Sets the target stage to build
        # target: # optional
        # Always attempt to pull a newer version of the image
        always_pull: true # optional
        # Comma-delimited list of build-time variables
        # build_args: # optional
        # Comma-delimited list of images to consider as cache sources
        # cache_froms: # optional
        # Comma-delimited list of labels to add to the built image
        # labels: # optional
        # Adds labels with git repository information to the built image
        # add_git_labels: # optional
        # Whether to push the image
        # push: # optional, default is true
  
  build-chain-db-open-server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build and push auth server
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: niklabh # optional
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }} # optional
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: # optional
        # Docker repository to tag the image with
        repository: niklabh/polkassembly-chain-db-open-server
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: latest # optional
        # Automatically tags the built image with the git reference as per the readme
        tag_with_ref: true # optional
        # Automatically tags the built image with the git short SHA as per the readme
        tag_with_sha: true # optional
        # Path to the build context
        path: chain-db-open-server
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # dockerfile: # optional
        # Sets the target stage to build
        # target: # optional
        # Always attempt to pull a newer version of the image
        always_pull: true # optional
        # Comma-delimited list of build-time variables
        # build_args: # optional
        # Comma-delimited list of images to consider as cache sources
        # cache_froms: # optional
        # Comma-delimited list of labels to add to the built image
        # labels: # optional
        # Adds labels with git repository information to the built image
        # add_git_labels: # optional
        # Whether to push the image
        # push: # optional, default is true
  build-chain-db-watcher:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build and push auth server
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: niklabh # optional
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }} # optional
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: # optional
        # Docker repository to tag the image with
        repository: niklabh/polkassembly-chain-db-watcher
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: latest # optional
        # Automatically tags the built image with the git reference as per the readme
        tag_with_ref: true # optional
        # Automatically tags the built image with the git short SHA as per the readme
        tag_with_sha: true # optional
        # Path to the build context
        path: chain-db-watcher
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # dockerfile: # optional
        # Sets the target stage to build
        # target: # optional
        # Always attempt to pull a newer version of the image
        always_pull: true # optional
        # Comma-delimited list of build-time variables
        # build_args: # optional
        # Comma-delimited list of images to consider as cache sources
        # cache_froms: # optional
        # Comma-delimited list of labels to add to the built image
        # labels: # optional
        # Adds labels with git repository information to the built image
        # add_git_labels: # optional
        # Whether to push the image
        # push: # optional, default is true
  build-health-monitor:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build and push auth server
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: niklabh # optional
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }} # optional
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: # optional
        # Docker repository to tag the image with
        repository: niklabh/polkassembly-health-monitor
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: latest # optional
        # Automatically tags the built image with the git reference as per the readme
        tag_with_ref: true # optional
        # Automatically tags the built image with the git short SHA as per the readme
        tag_with_sha: true # optional
        # Path to the build context
        path: health-monitor
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # dockerfile: # optional
        # Sets the target stage to build
        # target: # optional
        # Always attempt to pull a newer version of the image
        always_pull: true # optional
        # Comma-delimited list of build-time variables
        # build_args: # optional
        # Comma-delimited list of images to consider as cache sources
        # cache_froms: # optional
        # Comma-delimited list of labels to add to the built image
        # labels: # optional
        # Adds labels with git repository information to the built image
        # add_git_labels: # optional
        # Whether to push the image
        # push: # optional, default is true
  build-node-watcher:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build and push auth server
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: niklabh # optional
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }} # optional
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: # optional
        # Docker repository to tag the image with
        repository: niklabh/polkassembly-node-watcher
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: latest # optional
        # Automatically tags the built image with the git reference as per the readme
        tag_with_ref: true # optional
        # Automatically tags the built image with the git short SHA as per the readme
        tag_with_sha: true # optional
        # Path to the build context
        path: node-watcher
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        # dockerfile: # optional
        # Sets the target stage to build
        # target: # optional
        # Always attempt to pull a newer version of the image
        always_pull: true # optional
        # Comma-delimited list of build-time variables
        # build_args: # optional
        # Comma-delimited list of images to consider as cache sources
        # cache_froms: # optional
        # Comma-delimited list of labels to add to the built image
        # labels: # optional
        # Adds labels with git repository information to the built image
        # add_git_labels: # optional
        # Whether to push the image
        # push: # optional, default is true
  
